from __future__ import annotations

from typing import Protocol


class BodyBackend(Protocol):
    def connect(self) -> None: ...

    def close(self) -> None: ...

    def probe(self) -> dict[str, object]: ...

    def trigger_hotkey(self, hotkey: str) -> dict[str, object]: ...

    def apply_tracking(self, values: dict[str, float], *, source: str) -> dict[str, object]: ...
